-- Add up migration script here

CREATE TABLE PHENOTYPE (
    name TEXT PRIMARY KEY,
    variant TEXT NOT NULL
);

CREATE TABLE GENOTYPE (
    phenotype TEXT NOT NULL REFERENCES PHENOTYPE,
    -- Genes list
    ASIP1 TEXT,
    ASIP2 TEXT,
    TYRP1 TEXT,
    TYRP2 TEXT,
    TYR1 TEXT,
    TYR2 TEXT,
    MYO5A1 TEXT,
    MYO5A2 TEXT,
    OCA1 TEXT,
    OCA2 TEXT,
    MLPH1 TEXT,
    MLPH2 TEXT
    -- Potencially more to come
);

CREATE TABLE ANIMAL (
    id TEXT PRIMARY KEY,
    gender_male BOOLEAN NOT NULL,
    status TEXT,
    eye_color TEXT,
    hair TEXT,
    phenotype TEXT NOT NULL REFERENCES PHENOTYPE
);

CREATE TABLE LITTER (
    id TEXT PRIMARY KEY,
    mother TEXT NOT NULL REFERENCES ANIMAL,
    father TEXT NOT NULL REFERENCES ANIMAL
);

ALTER TABLE ANIMAL
ADD COLUMN litter TEXT REFERENCES LITTER;


CREATE TABLE PHOTO (
    path TEXT PRIMARY KEY,
    taken_date DATE
);

CREATE TABLE ANIMAL_PHOTO (
    animal TEXT NOT NULL REFERENCES ANIMAL,
    photo TEXT NOT NULL REFERENCES PHOTO
);

CREATE TABLE LITTER_PHOTO (
    litter TEXT NOT NULL REFERENCES LITTER,
    photo TEXT NOT NULL REFERENCES PHOTO
);
