-- Add up migration script here

CREATE TABLE PHENOTYPE (
    name TEXT PRIMARY KEY,
    variant TEXT NOT NULL
);

CREATE TABLE GENOTYPE (
    phenotype TEXT NOT NULL REFERENCES PHENOTYPE,
    genes JSON NOT NULL
    -- Genes list
    --ASIP1 TEXT,
    --ASIP2 TEXT,
    --TYRP1 TEXT,
    --TYRP2 TEXT,
    --TYR1 TEXT,
    --TYR2 TEXT,
    --MYO5A1 TEXT,
    --MYO5A2 TEXT,
    --OCA1 TEXT,
    --OCA2 TEXT,
    --MLPH1 TEXT,
    --MLPH2 TEXT,
    --PMEL1 TEXT,
    --PMEL2 TEXT,
    --ATP7A1 TEXT,
    --ATP7A2 TEXT,
    --KIT1 TEXT,
    --KIT2 TEXT,
    --MC1R1 TEXT,
    --MC1R2 TEXT,
    --AP3B1 TEXT,
    --AP3B2 TEXT,
    --U1 TEXT,
    --U2 TEXT,
    --RW1 TEXT,
    --RW2 TEXT,
    --SPL1 TEXT,
    --SPL2 TEXT,
    --RN1 TEXT,
    --RN2 TEXT,
    --FZ1 TEXT,
    --FZ2 TEXT
    -- Potencially more to come
);

CREATE TABLE ANIMAL (
    id TEXT PRIMARY KEY,
    gender_male BOOLEAN NOT NULL,
    status TEXT,
    eye_color TEXT,
    hair TEXT,
    phenotype TEXT NOT NULL REFERENCES PHENOTYPE
);

CREATE TABLE LITTER (
    id TEXT PRIMARY KEY,
    mother TEXT NOT NULL REFERENCES ANIMAL,
    father TEXT NOT NULL REFERENCES ANIMAL
);

ALTER TABLE ANIMAL
ADD COLUMN litter TEXT REFERENCES LITTER;


CREATE TABLE PHOTO (
    path TEXT PRIMARY KEY,
    taken_date DATE
);

CREATE TABLE ANIMAL_PHOTO (
    animal TEXT NOT NULL REFERENCES ANIMAL,
    photo TEXT NOT NULL REFERENCES PHOTO
);

CREATE TABLE LITTER_PHOTO (
    litter TEXT NOT NULL REFERENCES LITTER,
    photo TEXT NOT NULL REFERENCES PHOTO
);
