-- Add up migration script here

CREATE TABLE ANIMAL (
    id VARCHAR(10) PRIMARY KEY,
    gender_male BOOLEAN NOT NULL,
    status VARCHAR(20),
    eye_color VARCHAR(20),
    hair VARCHAR(20)
);

CREATE TABLE LITTER (
    id VARCHAR(10) PRIMARY KEY,
    mother VARCHAR(10) NOT NULL REFERENCES ANIMAL,
    father VARCHAR(10) NOT NULL REFERENCES ANIMAL
);

ALTER TABLE ANIMAL
ADD COLUMN litter VARCHAR(10) REFERENCES LITTER;