[workspace]

members = [
    "backend",
    "frontend",
    "common",
    "backend-api",
    "db",
    "csv-reader"
]

default-members = [
    "backend"
]

[profile.web]
inherits = "release"
lto = true
opt-level = 's'
