[workspace]

members = [
    "backend",
    "frontend",
    "common",
    "backend-api",
    "db"
]

default-members = [
    "backend"
]

[profile.dev.package."*"]
opt-level = 2

[profile.dev.package.sqlx-macros]
opt-level = 3