version: '0.1.1'
services:
  db-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pgdb
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./db/data
        target: /var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    image: mwasilewski12/mouse-server
    restart: always
    ports:
      - "80:8000"
    volumes:
      - type: bind
        source: ./files
        target: /usr/bin/files
      - type: bind
        source: ./public
        target: /usr/bin/public
    depends_on:
      - db-postgres
