version: '0.1.0'
services:
  db-postgres:
    image: postgres
    restart: always
    container_name: db-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pgdb
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./db/data
        target: /var/lib/postgresql/data
  server:
    image: rust-server
    restart: always
    container_name: server
    ports:
      - "80:8000"
    volumes:
      - type: bind
        source: ./files
        target: /usr/bin/files
      - type: bind
        source: ./public
        target: /usr/bin/public
    links:
      - db-postgres
